### ISSUE TITLE
AMQPRuntimeException: Connection timed out every day

### ISSUE THREAD

**Issue by Tetragramat** [videlalvaro/RabbitMqBundle#315]
Hi, I'm getting every day this exception in my consumers.
PhpAmqpLib\Exception\AMQPRuntimeException: Error Connecting to server (110): Connection timed out

This exception is thrown every night when there are new messages to consume. After restart everything works fine until next night.
I do not know what should be wrong.

my configuration:
```yaml
old_sound_rabbit_mq:
    connections:
        default: { host: %rabbit_mq_host%, port: %rabbit_mq_port%, user: %rabbit_mq_user%, password: %rabbit_mq_password%, vhost: %rabbit_mq_vhost% }
    producers:
        notifiable_event:
            connection: default
            exchange_options:   {name: 'notifiable-event', type: direct, auto_delete: false, durable: true}
        general_notification:
            connection: default
            exchange_options:   {name: 'general-notification', type: direct, auto_delete: false, durable: true}
    consumers:
        notifiable_event:
            connection: default
            exchange_options: {name: 'notifiable-event', type: direct}
            queue_options: {name: 'notifiable-event'}
            callback: netreal_notification.consumer.general_notification
        general_notification:
            connection: default
            exchange_options: {name: 'general-notification', type: direct}
            queue_options: {name: 'general-notification'}
            callback: namshi.notification.consumer
```

I'm not sure, but should be that I have heartbeat set as 0?
```
PhpAmqpLib\Wire\IO\StreamIO {#211
          #host: "172.16.0.36"
          #port: 5672
          #connection_timeout: 3
          #read_write_timeout: 3
          #context: null
          #keepalive: false
          #heartbeat: 0
          #last_read: null
          #last_write: null
          -sock: false
          -canDispatchPcntlSignal: false
        }
```
